//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.6

use sea_orm::entity::prelude::*;
use serde::Serialize;
use utoipa::ToSchema;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, ToSchema, Serialize)]
#[sea_orm(table_name = "rules")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub rule_id: i32,
    pub status: i32,
    #[schema(value_type = String)]
    pub create_time: DateTime,
    #[schema(value_type = String)]
    pub update_time: DateTime,
    pub name: String,
    pub desc: String,
    pub front_path: Option<String>,
    pub condition: Option<String>,
    pub menu: i32,
    pub order: Option<i32>,
    pub icon: Option<String>,
    pub method: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
