//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.6

use sea_orm::entity::prelude::*;
use serde::Serialize;
use utoipa::ToSchema;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, ToSchema, Serialize)]
#[sea_orm(table_name = "coupons")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub r#type: i32,
    #[sea_orm(column_type = "Double")]
    pub value: f64,
    pub total: i32,
    pub used: i32,
    #[sea_orm(column_type = "Double")]
    pub min_price: f64,
    pub start_time: String,
    pub end_time: String,
    pub status: i32,
    pub order: i32,
    pub desc: String,
    pub create_time: String,
    pub update_time: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
