//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.6

use sea_orm::entity::prelude::*;
use serde::Serialize;
use utoipa::ToSchema;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, ToSchema, Serialize)]
#[sea_orm(table_name = "goods")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub title: String,
    pub category_id: i32,
    pub cover: String,
    pub desc: String,
    pub unit: String,
    pub stock: i32,
    pub min_stock: i32,
    pub status: i32,
    pub stock_display: i32,
    pub min_price: String,
    pub min_ori_price: String,
    pub is_check: i32,
    pub create_time: String,
    pub update_time: String,
    pub delete_time: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
