//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.6

pub mod prelude;

pub mod admins;
pub mod coupons;
pub mod goods;
pub mod image_classes;
pub mod images;
pub mod notices;
pub mod roles;
pub mod rules;
pub mod skus;
pub mod user_levels;
pub mod users;
