//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.6

pub use super::admins::Entity as Admins;
pub use super::notices::Entity as Notices;
pub use super::roles::Entity as Roles;
pub use super::rules::Entity as Rules;
pub use super::users::Entity as Users;
