//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.6

pub use super::admins::Entity as Admins;
pub use super::coupons::Entity as Coupons;
pub use super::goods::Entity as Goods;
pub use super::image_classes::Entity as ImageClasses;
pub use super::images::Entity as Images;
pub use super::notices::Entity as Notices;
pub use super::roles::Entity as Roles;
pub use super::rules::Entity as Rules;
pub use super::skus::Entity as Skus;
pub use super::user_levels::Entity as UserLevels;
pub use super::users::Entity as Users;
